# Generated by Django 6.0.2 on 2026-02-26 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='categories.category')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('category', 'month', 'year')},
            },
        ),
    ]
