# Generated by Django 6.0.2 on 2026-03-02 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='name',
        ),
    ]
