# Generated by Django 6.0.2 on 2026-06-30 14:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_user'),
        ('goals', '0003_goal_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goal',
            unique_together={('user', 'category', 'month', 'year')},
        ),
    ]
