# Generated by Django 6.0.2 on 2026-02-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transiction',
            new_name='Transaction',
        ),
    ]
